import { TreeSelector } from "Application/components";
import { Tree } from "Application/types";

const countries = {
  "Belgium": [
    "Bruges",
    "Mechelen",
    "Ghent",
    "Namur",
    "Brussels",
    "Antwerp",
    "Leuven",
    "Charleroi",
    "Kortrijk",
  ],
  "France": [
    "Paris",
    "Marseille",
    "Lyon",
    "Toulouse",
    "Nice",
    "Nantes",
    "Strasbourg",
    "Montpellier",
    "Bordeaux",
    "Lille",
    "Rennes",
    "Reims",
    "Le",
    "Saint",
    "Toulon",
    "Grenoble",
  ],
  "Germany": [
    "Berlin",
    "Hamburg",
    "Munich",
    "Frankfurt",
    "Cologne",
    "Leipzig",
    "Stuttgart",
    "Düsseldorf",
    "Bremen",
    "Nuremberg",
    "Bonn",
    "Dresden",
    "Heidelberg",
    "Dortmund",
    "Aachen",
    "Bielefeld",
    "Augsburg",
    "Bremerhaven",
  ],
};

const retailers = [
  "Walmart",
  "The Kroger Co.",
  "Amazon",
  "Costco",
  "The Home Depot",
  "Walgreens Boots Alliance",
  "CVS Health Corporation",
  "Target",
  "Lowe's Companies",
  "Albertsons Companies",
  "Royal Ahold Delhaize USA",
  "Apple Stores / iTunes",
  "Best Buy",
  "McDonald's",
  "Publix Super Markets",
  "TJX Companies",
  "Aldi",
  "Macy's",
  "Dollar General",
  "H-E-B Grocery",
  "Dollar Tree",
  "Rite Aid",
  "Kohl's",
  "Verizon Wireless",
  "YUM! Brands",
  "Meijer",
  "Ace Hardware",
  "Starbucks",
  "Wakefern / ShopRite",
  "Nordstrom",
  "Sears Holdings",
  "7-Eleven",
  "Ross Stores",
  "Subway",
  "AT&T Wireless",
  "Gap",
  "BJ's Wholesale Club",
  "J.C. Penney Co.",
  "Bed Bath & Beyond",
  "Qurate Retail Group (formerly QVC)",
  "L Brands",
  "Menard",
  "Southeastern Grocers",
  "Health Mart Systems",
  "Good Neighbor Pharmacy",
  "Hy-Vee",
  "AutoZone",
  "Alimentation Couche-Tard",
  "Wendy's",
  "Chick-fil-A",
  "Dunkin' Brands Group",
  "Giant Eagle",
  "O'Reilly Auto Parts",
  "Wegmans Food Market",
  "Burger King Worldwide",
  "Dick's Sporting Goods",
  "Darden Restaurants",
  "PetSmart",
  "Sherwin-Williams",
  "Staples",
  "Army & Air Force Exchange",
  "Bass Pro",
  "Tractor Supply Co.",
  "WinCo Foods",
  "Save-A-Lot",
  "Ascena Retail Group",
  "Dine Brands Global",
  "Office Depot",
  "GameStop",
  "Dillard's",
  "Burlington Coat Factory",
  "Toys \"R\" Us",
  "Ulta Salon, Cosmetics & Fragrance",
  "Sephora (LVMH)",
  "Foot Locker",
  "Ikea North American Svcs.",
  "Domino's Pizza",
  "Academy",
  "Panera Bread Company",
  "AVB Brandsource",
  "Signet Jewelers",
  "Big Lots",
  "Williams-Sonoma",
  "Saks Fifth Avenue / Lord & Taylor",
  "Defense Commissary Agency",
  "Hobby Lobby Stores",
  "Speedway",
  "Michaels Stores",
  "True Value Co.",
  "Discount Tire",
  "Sprouts Farmers Market",
  "Exxon Mobil Corporation",
  "Neiman Marcus",
  "Jack in the Box",
  "Shell Oil Company",
  "Sonic",
  "Chipotle Mexican Grill",
  "SUPERVALU",
  "Belk",
  "Petco Animal Supplies",
];

const firstNames = [
 "James",
 "Mary",
 "Michael",
 "Patricia",
 "Robert",
 "Jennifer",
 "John",
 "Linda",
 "David",
 "Elizabeth",
 "William",
 "Barbara",
 "Richard",
 "Susan",
 "Joseph",
 "Jessica",
 "Thomas",
 "Karen",
 "Christopher",
 "Sarah",
 "Charles",
 "Lisa",
 "Daniel",
 "Nancy",
 "Matthew",
 "Sandra",
 "Anthony",
 "Betty",
 "Mark",
 "Ashley",
 "Donald",
 "Emily",
 "Steven",
 "Kimberly",
 "Andrew",
 "Margaret",
 "Paul",
 "Donna",
 "Joshua",
 "Michelle",
 "Kenneth",
 "Carol",
 "Kevin",
 "Amanda",
 "Brian",
 "Melissa",
 "Timothy",
 "Deborah",
 "Ronald",
 "Stephanie",
 "George",
 "Rebecca",
 "Jason",
 "Sharon",
 "Edward",
 "Laura",
 "Jeffrey",
 "Cynthia",
 "Ryan",
 "Dorothy",
 "Jacob",
 "Amy",
 "Nicholas",
 "Kathleen",
 "Gary",
 "Angela",
 "Eric",
 "Shirley",
 "Jonathan",
 "Emma",
 "Stephen",
 "Brenda",
 "Larry",
 "Pamela",
 "Justin",
 "Nicole",
 "Scott",
 "Anna",
 "Brandon",
 "Samantha",
 "Benjamin",
 "Katherine",
 "Samuel",
 "Christine",
 "Gregory",
 "Debra",
 "Alexander",
 "Rachel",
 "Patrick",
 "Carolyn",
 "Frank",
 "Janet",
 "Raymond",
 "Maria",
 "Jack",
 "Olivia",
 "Dennis",
 "Heather",
 "Jerry",
 "Helen",
 "Tyler",
 "Catherine",
 "Aaron",
 "Diane",
 "Jose",
 "Julie",
 "Adam",
 "Victoria",
 "Nathan",
 "Joyce",
 "Henry",
 "Lauren",
 "Zachary",
 "Kelly",
 "Douglas",
 "Christina",
 "Peter",
 "Ruth",
 "Kyle",
 "Joan",
 "Noah",
 "Virginia",
 "Ethan",
 "Judith",
 "Jeremy",
 "Evelyn",
 "Christian",
 "Hannah",
 "Walter",
 "Andrea",
 "Keith",
 "Megan",
 "Austin",
 "Cheryl",
 "Roger",
 "Jacqueline",
 "Terry",
 "Madison",
 "Sean",
 "Teresa",
 "Gerald",
 "Abigail",
 "Carl",
 "Sophia",
 "Dylan",
 "Martha",
 "Harold",
 "Sara",
 "Jordan",
 "Gloria",
 "Jesse",
 "Janice",
 "Bryan",
 "Kathryn",
 "Lawrence",
 "Ann",
 "Arthur",
 "Isabella",
 "Gabriel",
 "Judy",
 "Bruce",
 "Charlotte",
 "Logan",
 "Julia",
 "Billy",
 "Grace",
 "Joe",
 "Amber",
 "Alan",
 "Alice",
 "Juan",
 "Jean",
 "Elijah",
 "Denise",
 "Willie",
 "Frances",
 "Albert",
 "Danielle",
 "Wayne",
 "Marilyn",
 "Randy",
 "Natalie",
 "Mason",
 "Beverly",
 "Vincent",
 "Diana",
 "Liam",
 "Brittany",
 "Roy",
 "Theresa",
 "Bobby",
 "Kayla",
 "Caleb",
 "Alexis",
 "Bradley",
 "Doris",
 "Russell",
 "Lori",
 "Lucas",
 "Tiffany",
];

const lastNames = [
  "Smith",
  "Johnson",
  "Williams",
  "Brown",
  "Jones",
  "Garcia",
  "Miller",
  "Davis",
  "Rodriguez",
  "Martinez",
  "Hernandez",
  "Lopez",
  "Gonzales",
  "Wilson",
  "Anderson",
  "Thomas",
  "Taylor",
  "Moore",
  "Jackson",
  "Martin",
  "Lee",
  "Perez",
  "Thompson",
  "White",
  "Harris",
  "Sanchez",
  "Clark",
  "Ramirez",
  "Lewis",
  "Robinson",
  "Walker",
  "Young",
  "Allen",
  "King",
  "Wright",
  "Scott",
  "Torres",
  "Nguyen",
  "Hill",
  "Flores",
  "Green",
  "Adams",
  "Nelson",
  "Baker",
  "Hall",
  "Rivera",
  "Campbell",
  "Mitchell",
  "Carter",
  "Roberts",
  "Gomez",
  "Phillips",
  "Evans",
  "Turner",
  "Diaz",
  "Parker",
  "Cruz",
  "Edwards",
  "Collins",
  "Reyes",
  "Stewart",
  "Morris",
  "Morales",
  "Murphy",
  "Cook",
  "Rogers",
  "Gutierrez",
  "Ortiz",
  "Morgan",
  "Cooper",
  "Peterson",
  "Bailey",
  "Reed",
  "Kelly",
  "Howard",
  "Ramos",
  "Kim",
  "Cox",
  "Ward",
  "Richardson",
  "Watson",
  "Brooks",
  "Chavez",
  "Wood",
  "James",
  "Bennet",
  "Gray",
  "Mendoza",
  "Ruiz",
  "Hughes",
  "Price",
  "Alvarez",
  "Castillo",
  "Sanders",
  "Patel",
  "Myers",
  "Long",
  "Ross",
  "Foster",
  "Jimenez",
];

function makeId(): string {
  return Math.random().toString(36).slice(2);
}

function makeRetailers(parent: Tree, depth: number): Tree[] {
  const r = Math.random() * 0.5 + 0.2;
  return retailers.filter(() => Math.random() < r).map(
    retailer => {
      const tree: Tree = {
        id: makeId(),
        label: retailer,
        children: null,
        parent,
        depth,
      };

      tree.children = {
        label: "Staff",
        nodes: makeStaff(tree, depth + 1),
      };

      return tree;
    }
  );
}

function makeStaff(parent: Tree, depth: number): Tree[] {
  const r = Math.random() * 0.9 + 0.1;
  return firstNames.filter(() => Math.random() < r).map(
    staff => ({
      id: makeId(),
      label: `${staff} ${lastNames[Math.floor(Math.random() * lastNames.length)]}`,
      children: null,
      parent,
      depth,
    })
  );
}

const root: Tree = {
  id: makeId(),
  label: "Europe",
  parent: null,
  children: null,
  depth: 0,
};

root.children = {
  label: "Countries",
  nodes: Object.entries(countries).map(
    ([ country, cities ]) => {
      const tree: Tree = {
        id: makeId(),
        label: country,
        children: null,
        parent: root,
        depth: 1,
      }

      tree.children = {
        label: "Cities",
        nodes: cities.map(
          city => {
            const subtree: Tree = {
              id: makeId(),
              label: city,
              parent: tree,
              children: null,
              depth: 2,
            }

            subtree.children = {
              label: "Retailers",
              nodes: makeRetailers(subtree, 3),
            };

            return subtree;
          }
        ),
      };

      return tree;
    }
  ),
};

export function TreeSelectorExample(): JSX.Element {
  return (
    <TreeSelector
      root={root}
    />
  );
}
